# Generated by Django 4.2.6 on 2023-11-29 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('cookingSteps', models.TextField()),
                ('cookingTime', models.DurationField()),
                ('image', models.ImageField(upload_to='cooking_image/')),
                ('author', models.ForeignKey(db_column='author', max_length=30, on_delete=django.db.models.deletion.PROTECT, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_consumption', models.CharField(max_length=20)),
                ('consistency', models.CharField(max_length=20)),
                ('feed_temperature', models.CharField(max_length=20)),
                ('method_of_preparation', models.CharField(max_length=20)),
                ('by_appointment', models.CharField(max_length=20)),
                ('nameRecipes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.recipes')),
            ],
        ),
    ]
