# Generated by Django 4.2.6 on 2023-11-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_recipes_ingredients_alter_recipes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cookingTime',
            field=models.CharField(max_length=20),
        ),
    ]
